### ISSUE TITLE
TypeError: 'undefined' is not a constructor (evaluating 'new BlobBuilder()')

### ISSUE THREAD

**Issue by Neelfyn** [richardassar/pngcrush.js#2]
I get this error when I try to crush an image on the [demo page](http://richardassar.github.com/pngcrush.js/) using Safari 6.0.
zip.js seems to have a [similar issue](https://github.com/gildas-lormeau/zip.js/issues/14).

**Comment by richardassar** [comment]
Sorry to hear about the error.

Could you please give me the version of safari that you're currently
running?

As an interim solution you can use Chrome.

The problem is possibly that BlobBuilder is deprecated in place of `new
Blob(...)`

Thanks for the bug report.

**Comment by Neelfyn** [comment]
That's Safari 6.0 (8536.25) on OS X 10.8.
Using another browser is not a problem for me, but it would be neat if it worked everywhere.

You're right about the deprecation, here's the WebKit changeset: http://trac.webkit.org/changeset/115666

I played around a bit with it, I'm not sure I'm doing it right, but replacing:

```
var blobBuilder = new BlobBuilder();
blobBuilder.append(fileData);
var blob = blobBuilder.getBlob('image/png');
```

with:

```
var blob = new Blob([fileData], {type: 'image/png'});
```

seems to work, but the "download" button doesn't work:

```
Safari can't open "blob:file:///21a917a7-882e-4092-aeac-c3f08870fb4c" because OS X doesn't recognize Internet addresses starting with "blob :".
```

Same problem as in the zip.js issue, basically.
You can still save the image from the preview though, which is better than nothing.

**Comment by richardassar** [comment]
The download link is a problem present in Firefox also ("download"
attribute is ignored).

Seems that blobs can't be given a URL, so FileWriter has to be used (not
available in Chrome).

It's very annoying.

If your fix works in Chrome / FF then please feel welcome to submit a pull
request.

Thanks :)

**Comment by Neelfyn** [comment]
Quickly tested it in Firefox 15 and Chrome 21, and it looks like everything works as expected.
